name: CI

on:
  push:
  pull_request:

jobs:
  teste:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Backend
        env:
          NODE_ENV: test
          JWT_SECRET: abc123
        run: |
          cd backend
          yarn
          yarn test

      - name: Frontend
        run: |
          cd frontend
          yarn
          yarn build