name: CI

on:
  push:
  pull_request:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 🔍 DEBUG (opcional, mas útil)
      - name: Ver estrutura
        run: ls -R

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 🔥 BACKEND (corrigido aqui)
      - name: Backend
        run: |
          cd blackend
          yarn
          yarn test
        env:
          NODE_ENV: test
          JWT_SECRET: abc123

      # 🔥 FRONTEND
      - name: Frontend
        run: |
          cd frontend
          yarn
          yarn build